# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob notify prompt_subst
unsetopt beep nomatch
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/devyn/.zshrc'

autoload -Uz compinit promptinit vcs_info colors
compinit
promptinit

source /home/devyn/scripts/dotfiles/zsh-git-prompt/zshrc.sh

function lastExit() {
	local LAST_EXIT_CODE=$?
	if [[ $LAST_EXIT_CODE -ne 0 ]]; then
		local EXIT_CODE_PROMPT="($LAST_EXIT_CODE) "
		echo "$EXIT_CODE_PROMPT"
	fi
}

RPROMPT='$(git_super_status)'

PROMPT="%F{249}{ %F{213}%n%F{248}@%F{199}%M%F{249} } %D{%A, %B %d - %H:%M}"$'\n''$(lastExit)'"%~%F{white} > "

source $HOME/.aliases
source $HOME/.profile

